### ISSUE TITLE
TODO: Exportar banco de dados para o excel

### ISSUE THREAD

**Issue by dgsmiley18** [Jeeffsantoos/AP2_PRATICA_PYTHON#25]
No trabalho é requisitado a manipulação de arquivos, a ideia é inserir exportar todas as informações do banco de dados para um bloco de texto

**Comment by Jeeffsantoos** [comment]
Não é opcional ?

**Comment by dgsmiley18** [comment]
> Não é opcional ?

Não, é obrigatório

Deve-se implementar:
> Tratamento de exceções(Opcional)
> listas
> Manipulação de Arquivos
> Os dados campos referentes às informações de Clientes, Motocicletas
> Vendas deverão ser de sua escolha.
